import { Roboto } from "next/font/google";
import '../app/globals.css';
import Header from "../components/Header";
import DHeader from "../components/dHeader";
import { Providers } from "./providers";

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Providers>
          <Header />
          <main>
            {children}
          </main>
          <DHeader />
        </Providers>
      </body>
    </html>
  );
}